const jwt = require("jsonwebtoken");
require('dotenv').config();
function generateToken(user) {
  return jwt.sign(
    { userID: user.id, role: user.role }, // jwt is storing the user id as generated by the uuid7 in the scheme rather than the '_id' provided by mongoDB by it's own
    process.env.ACCESS_SECRET,
    {expiresIn:'1h'}
);
}
module.exports= generateToken;