const jwt = require("jsonwebtoken");
require('dotenv').config();
function generateToken(user) {
  return jwt.sign(
    { userID: user.id, roles: user.roles }, // jwt is storing the user id as generated by the uuid7 in the scheme rather than the '_id' provided by mongoDB by it's own
    process.env.SECRET,
    {expiresIn:'1h'}
);
}
module.exports= generateToken;