const jwt= require('jsonwebtoken')
require('dotenv').config();
const checkAuth= (req,res,next)=>{
    console.log(req)
    const token = req.cookies.authToken // check the cookies to find 'authToken' as generated by the login route
    if (!token) return res.status(401).json("Token not found");
    jwt.verify(token, process.env.ACCESS_SECRET,(err,user)=>{
        if (err) return res.status(403).json({message: "Access forbidden, token invalid"});
        req.user= user;
        next();
    })
}
module.exports= checkAuth